//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIKITCHEN.DBL.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_UNIKITCHENEntities : DbContext
    {
        public DB_UNIKITCHENEntities(string c)
            : base(c)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_APPENDIX> T_APPENDIX { get; set; }
        public virtual DbSet<T_CATEGORY> T_CATEGORY { get; set; }
        public virtual DbSet<T_EMPLOYEE> T_EMPLOYEE { get; set; }
        public virtual DbSet<T_FIRMS> T_FIRMS { get; set; }
        public virtual DbSet<T_MEALPRICE> T_MEALPRICE { get; set; }
        public virtual DbSet<T_MEALS> T_MEALS { get; set; }
        public virtual DbSet<T_MENUDAY> T_MENUDAY { get; set; }
        public virtual DbSet<T_MENUDAYLINE> T_MENUDAYLINE { get; set; }
        public virtual DbSet<T_OPERATION> T_OPERATION { get; set; }
        public virtual DbSet<T_OPERATIONLINE> T_OPERATIONLINE { get; set; }
        public virtual DbSet<T_SPECODE> T_SPECODE { get; set; }
        public virtual DbSet<T_SYS_MENUS> T_SYS_MENUS { get; set; }
        public virtual DbSet<T_SYS_USER> T_SYS_USER { get; set; }
        public virtual DbSet<T_SYS_USERGROUP> T_SYS_USERGROUP { get; set; }
        public virtual DbSet<T_SYS_USERMENU> T_SYS_USERMENU { get; set; }
        public virtual DbSet<T_UOM> T_UOM { get; set; }
        public virtual DbSet<T_Z> T_Z { get; set; }
    
        public virtual ObjectResult<SP_GETMENUS_Result> SP_GETMENUS(Nullable<int> cAT_ID)
        {
            var cAT_IDParameter = cAT_ID.HasValue ?
                new ObjectParameter("CAT_ID", cAT_ID) :
                new ObjectParameter("CAT_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GETMENUS_Result>("SP_GETMENUS", cAT_IDParameter);
        }
    
        public virtual ObjectResult<SP_GETMENUSDAILY_Result> SP_GETMENUSDAILY(Nullable<int> cAT_ID)
        {
            var cAT_IDParameter = cAT_ID.HasValue ?
                new ObjectParameter("CAT_ID", cAT_ID) :
                new ObjectParameter("CAT_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GETMENUSDAILY_Result>("SP_GETMENUSDAILY", cAT_IDParameter);
        }
    
        public virtual ObjectResult<SP_GETOPERATIONOFTHEDAYE_Result> SP_GETOPERATIONOFTHEDAYE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GETOPERATIONOFTHEDAYE_Result>("SP_GETOPERATIONOFTHEDAYE");
        }
    
        public virtual ObjectResult<SP_GETOPERATIONS_Result> SP_GETOPERATIONS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GETOPERATIONS_Result>("SP_GETOPERATIONS");
        }
    }
}
