//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIKITCHEN.DBL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_APPENDIX
    {
        public int A_ID { get; set; }
        public string A_NO { get; set; }
        public Nullable<System.DateTime> A_DATE { get; set; }
        public Nullable<int> A_F_ID { get; set; }
        public string A_CONTRACTNO { get; set; }
        public Nullable<double> A_PRICE { get; set; }
        public Nullable<System.DateTime> A_BGDATE { get; set; }
        public Nullable<System.DateTime> A_ENDATE { get; set; }
        public Nullable<short> A_STATUS { get; set; }
    }
}
