//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIKITCHEN.DBL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EMPLOYEE
    {
        public int E_ID { get; set; }
        public Nullable<int> E_F_ID { get; set; }
        public string E_CODE { get; set; }
        public string E_NAME { get; set; }
        public string E_SNAME { get; set; }
        public Nullable<short> E_STATUS { get; set; }
    }
}
