//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIKITCHEN.DBL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FIRMS
    {
        public int F_ID { get; set; }
        public string F_CODE { get; set; }
        public string F_NAME { get; set; }
        public Nullable<short> F_STATUS { get; set; }
    }
}
