//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIKITCHEN.DBL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MEALS
    {
        public int M_ID { get; set; }
        public Nullable<int> M_CAT_ID { get; set; }
        public string M_CODE { get; set; }
        public string M_NAME { get; set; }
        public Nullable<int> M_OU_ID { get; set; }
        public Nullable<double> M_COFISENT { get; set; }
        public Nullable<short> M_STATUS { get; set; }
    }
}
