//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIKITCHEN.DBL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MENUDAY
    {
        public int MD_ID { get; set; }
        public Nullable<System.DateTime> MD_DATE { get; set; }
        public Nullable<System.TimeSpan> MD_BLBGTIME { get; set; }
        public Nullable<System.TimeSpan> MD_BLENTIME { get; set; }
        public Nullable<int> MD_U_ID { get; set; }
        public Nullable<System.DateTime> MD_CRDATE { get; set; }
        public Nullable<short> MD_STATUS { get; set; }
    }
}
