//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIKITCHEN.DBL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MENUDAYLINE
    {
        public int MDL_ID { get; set; }
        public Nullable<int> MDL_MD_ID { get; set; }
        public Nullable<int> MDL_M_ID { get; set; }
        public Nullable<int> MDL_UO_ID { get; set; }
        public Nullable<decimal> MDL_QTY { get; set; }
        public Nullable<short> MDL_STATUS { get; set; }
    }
}
