//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIKITCHEN.DBL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MEALPRICE
    {
        public int MP_ID { get; set; }
        public Nullable<int> MP_M_ID { get; set; }
        public Nullable<System.DateTime> MP_BGDATE { get; set; }
        public Nullable<System.DateTime> MP_ENDATE { get; set; }
        public Nullable<double> MP_AMOUNT { get; set; }
        public Nullable<short> MP_STATUS { get; set; }
        public Nullable<int> MP_U_ID { get; set; }
        public Nullable<System.DateTime> MP_CRDATE { get; set; }
    }
}
