//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIKITCHEN.DBL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OPERATIONLINE
    {
        public int OPRL_ID { get; set; }
        public Nullable<int> ORRL_OPR_ID { get; set; }
        public Nullable<int> OPRL_M_ID { get; set; }
        public Nullable<int> OPRL_UOM_ID { get; set; }
        public Nullable<double> OPRL_QTY { get; set; }
        public Nullable<double> OPRL_PRICE { get; set; }
        public Nullable<double> OPRL_TOTAL { get; set; }
        public short OPRL_STATUS { get; set; }
    }
}
