//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIKITCHEN.DBL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SPECODE
    {
        public int SC_ID { get; set; }
        public string SC_TYPE { get; set; }
        public string SC_CODE { get; set; }
        public string SC_NAME { get; set; }
        public Nullable<bool> SC_STATUS { get; set; }
    }
}
