//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIKITCHEN.DBL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SYS_USER
    {
        public int U_ID { get; set; }
        public Nullable<int> U_TYPE { get; set; }
        public string U_CODE { get; set; }
        public string U_FIRSTNAME { get; set; }
        public string U_LASTNAME { get; set; }
        public string U_USERNAME { get; set; }
        public string U_PASSWORD { get; set; }
        public Nullable<bool> U_CHANGEPASS { get; set; }
        public Nullable<short> U_STATUS { get; set; }
        public string U_NOTE { get; set; }
        public string U_EMAIL { get; set; }
        public string U_TEL { get; set; }
        public Nullable<System.DateTime> U_CREATEDATE { get; set; }
        public string U_IMG { get; set; }
        public Nullable<short> U_FIRST { get; set; }
        public Nullable<System.DateTime> U_LASTLOGIN_DATE { get; set; }
    }
}
