//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIKITCHEN.DBL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SYS_MENUS
    {
        public int MNU_ID { get; set; }
        public Nullable<int> MNU_PARENT { get; set; }
        public Nullable<int> MNU_M_ID { get; set; }
        public string MNU_CODE { get; set; }
        public string MNU_CAPTION1 { get; set; }
        public string MNU_CAPTION2 { get; set; }
        public string MNU_CAPTION3 { get; set; }
        public string MNU_CAPTION4 { get; set; }
        public string MNU_PAGEURL { get; set; }
        public string MNU_CSSURL { get; set; }
        public Nullable<short> MNU_LEVEL { get; set; }
        public Nullable<short> MNU_ORDERBY { get; set; }
        public Nullable<short> MNU_STATUS { get; set; }
    }
}
