//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIKITCHEN.DBL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SYS_USERGROUP
    {
        public int UG_ID { get; set; }
        public string UG_CODE { get; set; }
        public string UG_NAME { get; set; }
        public Nullable<short> UG_STATUS { get; set; }
    }
}
