//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIKITCHEN.DBL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SYS_USERMENU
    {
        public int UM_ID { get; set; }
        public Nullable<int> UM_U_TYPE { get; set; }
        public Nullable<int> UM_U_ID { get; set; }
        public Nullable<int> UM_TYPE { get; set; }
        public Nullable<int> UM_MNU_ID { get; set; }
    }
}
