//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIKITCHEN.DBL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Z
    {
        public int Z_ID { get; set; }
        public string Z_NO { get; set; }
        public Nullable<System.DateTime> Z_DATE { get; set; }
        public Nullable<double> Z_AMOUNT { get; set; }
        public Nullable<int> Z_U_ID { get; set; }
        public Nullable<System.DateTime> Z_CRDATE { get; set; }
    }
}
